apiVersion: apps/v1
kind: Deployment

metadata:
  name: ironclad-app
  labels:
    app: ironclad-app

spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: ironclad-app

  template:
    metadata:
      labels:
        app: ironclad-app

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: ironclad-app

          image: sandy541998/ironclad-app:1.0.0
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: APP_ENV
              value: "dev"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 1