apiVersion: v1
kind: Service

metadata:
  name: ironclad-service
  labels:
    app: ironclad-app

spec:
  selector:
    app: ironclad-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort